--- 
- 
  become: true
  hosts: node1
  name: "Install Wget and NGINX"
  tasks: 
    - 
      name: "Install Wget"
      yum: 
        name: wget
        state: latest
    - 
      name: "Install nginx"
      yum: 
        name: nginx
        state: latest
